import { Metadata } from 'next';
import '/assets/css/signIn.css'
import 'antd/dist/reset.css';
import { Providers } from '@/redux/Provider';

export const metadata: Metadata = {
  title: 'TechHouse',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  }) {
  
  return (
    <html lang="en">
      <body>
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
