import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { Metadata } from 'next';
import '/assets/scss/style.scss';
import NextTopLoader from 'nextjs-toploader';
import Providers from '@/redux/Provider';
import dynamic from 'next/dynamic';
import FacebookChat from '@/components/FacebookChat';
const DynamicReduxProvider = dynamic(() => import('@/redux/Provider'), {
  ssr: false,
});

export const metadata: Metadata = {
  title: {
    default: 'TechHouse | Store online for everyone',
    template: '%s | Store online for everyone',
  },
  authors: [{ name: 'Viet luu' }],
  category: 'next.js',
  keywords: ['next.js', 'reactjs', 'typescript', 'strnix'],
  icons: { icon: '/next.svg', apple: '/next.svg' },
  appleWebApp: true,
  verification: {
    google: '13V7E2I7nCJk7IROlz05ZTirDn17vPbKRuAZRm_9H3E',
  },
  robots: {
    index: false,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: false,
      noimageindex: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  description: 'Generated by create next app',
  openGraph: {
    images: ['/assets/images/sp/iphone-12_2__3.jpg'],
  },
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      {children}
      <FacebookChat />
      <Footer />
    </>
  );
}
