import Footer from '@/components/Footer';
import Header from '@/components/Header';
import {api} from  '@/utils/api'
import Template from './template'
import { Metadata } from 'next';
import { cookies } from 'next/headers';
import Cookies from 'js-cookie';
import { Providers } from '@/redux/Provider';
export const metadata: Metadata = {
  title: 'TechHouse',
  description: 'Generated by create next app',
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
  }) {
 
  return (
    <html lang="en">
      <body>
        <Providers>
        <Header/>
        <Template>
        {children}
        </Template>
        <Footer />
       </Providers>
      </body>
    </html>
  );
}
