import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { Metadata } from 'next';
import '/assets/scss/style.scss';
import NextTopLoader from 'nextjs-toploader';
import Providers from '@/redux/Provider';
import dynamic from 'next/dynamic';
const DynamicReduxProvider = dynamic(() => import('@/redux/Provider'), {
  ssr: false,
});

export const metadata: Metadata = {
  title: 'TechHouse',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <DynamicReduxProvider>
          <NextTopLoader color="#fff" />
          <Header />
          {children}
          <Footer />
        </DynamicReduxProvider>
      </body>
    </html>
  );
}
